### ISSUE TITLE
AM Video Interstitial (Out-of-the-box) fatal exception

### ISSUE THREAD

**Issue by yoalex5** [prebid/prebid-mobile-android#152]
**Describe the bug**

**To Reproduce**
1. Play Video-Interstitial with AM SDK
Use specific VAST

``` XML
<VAST version="2.0"> 
	<Ad id="TestAd"> 
		<InLine> 
			<AdSystem>Rubicon Project</AdSystem> 
			<AdTitle>VAST 2.0 Linear Ad</AdTitle> 
			<Error>
				<![CDATA[https://myErrorURL/error]]>
			</Error> 
			<Impression>
				<![CDATA[]]>
			</Impression> 
			<Creatives> 
				<Creative id="2014" AdID="20150911" sequence="1"> 
					<Linear> 
						<Duration>00:00:15</Duration> 
						<TrackingEvents> 
							<Tracking event="creativeView">
								<![CDATA[]]>
							</Tracking> 
							<Tracking event="start">
								<![CDATA[]]>
							</Tracking> 
							<Tracking event="firstQuartile">
								<![CDATA[]]>
							</Tracking> 
							<Tracking event="midpoint">
								<![CDATA[]]>
							</Tracking> 
							<Tracking event="thirdQuartile">
								<![CDATA[]]>
							</Tracking> 
							<Tracking event="complete">
								<![CDATA[]]>
							</Tracking> 
						</TrackingEvents> 
						<VideoClicks> 
							<ClickThrough>
								<![CDATA[https://iwanttoberecycled.org/]]>
							</ClickThrough> 
							<ClickTracking>
								<![CDATA[]]>
							</ClickTracking> 
						</VideoClicks> 
						<MediaFiles> 
							<MediaFile delivery="progressive" bitrate="275" width="320" height="180" type="video/x-flv">
								<![CDATA[https://sneezy.aws.rubiconproject.com/rp-eng-soln/rp-qa-sites/videoTest/ad1/recycling_320_low.flv]]>
							</MediaFile> 
							<MediaFile delivery="progressive" bitrate="348" width="320" height="180" type="video/mp4">
								<![CDATA[https://sneezy.aws.rubiconproject.com/rp-eng-soln/rp-qa-sites/videoTest/ad1/recycling_320_low.mp4]]>
							</MediaFile> 
							<MediaFile delivery="progressive" bitrate="250" width="320" height="180" type="video/webm">
								<![CDATA[https://sneezy.aws.rubiconproject.com/rp-eng-soln/rp-qa-sites/videoTest/ad1/recycling_320_low.webm]]>
							</MediaFile> 
							<MediaFile delivery="progressive" bitrate="433" width="620" height="360" type="video/x-flv">
								<![CDATA[https://sneezy.aws.rubiconproject.com/rp-eng-soln/rp-qa-sites/videoTest/ad1/recycling_640_low.flv]]>
							</MediaFile> 
							<MediaFile delivery="progressive" bitrate="381" width="620" height="360" type="video/mp4">
								<![CDATA[https://sneezy.aws.rubiconproject.com/rp-eng-soln/rp-qa-sites/videoTest/ad1/recycling_640_low.mp4]]>
							</MediaFile> 
							<MediaFile delivery="progressive" bitrate="614" width="620" height="360" type="video/x-flv">
								<![CDATA[https://sneezy.aws.rubiconproject.com/rp-eng-soln/rp-qa-sites/videoTest/ad1/recycling_640_med.flv]]>
							</MediaFile> 
							<MediaFile delivery="progressive" bitrate="553" width="620" height="360" type="video/mp4">
								<![CDATA[https://sneezy.aws.rubiconproject.com/rp-eng-soln/rp-qa-sites/videoTest/ad1/recycling_640_med.mp4]]>
							</MediaFile> 
							<MediaFile delivery="progressive" bitrate="1024" width="620" height="360" type="video/x-flv">
								<![CDATA[https://sneezy.aws.rubiconproject.com/rp-eng-soln/rp-qa-sites/videoTest/ad1/recycling_640_high.flv]]>
							</MediaFile> 
							<MediaFile delivery="progressive" bitrate="983" width="620" height="360" type="video/mp4">
								<![CDATA[https://sneezy.aws.rubiconproject.com/rp-eng-soln/rp-qa-sites/videoTest/ad1/recycling_640_high.mp4]]>
							</MediaFile> 
							<MediaFile delivery="progressive" bitrate="1024" width="620" height="360" type="video/webm">
								<![CDATA[https://sneezy.aws.rubiconproject.com/rp-eng-soln/rp-qa-sites/videoTest/ad1/recycling_640_high.webm]]>
							</MediaFile> 
						</MediaFiles> 
					</Linear> 
				</Creative> 
				<Creative AdID="TestAd-Companion"> 
					<CompanionAds> 
						<Companion width="300" height="250"> 
							<StaticResource creativeType="image/jpeg">
								<![CDATA[https://sneezy.aws.rubiconproject.com/rp-eng-soln/rp-qa-sites/videoTest/ad1/recycling_300x250.jpg]]> 
							</StaticResource> 
							<TrackingEvents> 
								<Tracking event="creativeView">
									<![CDATA[]]>
								</Tracking> 
							</TrackingEvents> 
							<CompanionClickThrough> 
								<![CDATA[ https://iwanttoberecycled.org/]]> 
							</CompanionClickThrough> 
						</Companion> 
					</CompanionAds> 
				</Creative> 
			</Creatives> 
		</InLine> 
	</Ad> 
</VAST>
```

**Expected behavior**
Video should be playing

**Smartphone (please complete the following information):**
 - OS: Android
 - PB SDK version: 1.2 with #151
 - AM SDK version: 17.1.3

**Additional context**
Error
``` 
10-24 14:37:23.108 13856-13983/org.prebid.mobile.prebidjavademo E/LoadTask: Unexpected exception loading stream
    java.lang.IllegalStateException: Top bit not zero: -1710615546
        at com.google.android.gms.ads.exoplayer1.util.g.f(:com.google.android.gms.dynamite_adsdynamite@16089056@16.0.89 (040800-239467275):20)
        at com.google.android.gms.ads.exoplayer1.extractor.mp4.f.a(:com.google.android.gms.dynamite_adsdynamite@16089056@16.0.89 (040800-239467275):42)
        at com.google.android.gms.ads.exoplayer1.extractor.h.c(:com.google.android.gms.dynamite_adsdynamite@16089056@16.0.89 (040800-239467275):21)
        at com.google.android.gms.ads.exoplayer1.upstream.r.run(:com.google.android.gms.dynamite_adsdynamite@16089056@16.0.89 (040800-239467275):9)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
10-24 14:37:23.109 13856-13906/org.prebid.mobile.prebidjavademo E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
10-24 14:37:23.111 13856-13982/org.prebid.mobile.prebidjavademo E/ExoPlayerImplInternal: Internal track renderer error.
    com.google.android.gms.ads.exoplayer1.d: com.google.android.gms.ads.exoplayer1.upstream.t: Unexpected IllegalStateException: Top bit not zero: -1710615546
        at com.google.android.gms.ads.exoplayer1.q.a(:com.google.android.gms.dynamite_adsdynamite@16089056@16.0.89 (040800-239467275):153)
        at com.google.android.gms.ads.exoplayer1.j.handleMessage(:com.google.android.gms.dynamite_adsdynamite@16089056@16.0.89 (040800-239467275):82)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
        at com.google.android.gms.ads.exoplayer1.util.h.run(:com.google.android.gms.dynamite_adsdynamite@16089056@16.0.89 (040800-239467275):4)
     Caused by: com.google.android.gms.ads.exoplayer1.upstream.t: Unexpected IllegalStateException: Top bit not zero: -1710615546
        at com.google.android.gms.ads.exoplayer1.upstream.r.run(:com.google.android.gms.dynamite_adsdynamite@16089056@16.0.89 (040800-239467275):19)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.IllegalStateException: Top bit not zero: -1710615546
        at com.google.android.gms.ads.exoplayer1.util.g.f(:com.google.android.gms.dynamite_adsdynamite@16089056@16.0.89 (040800-239467275):20)
        at com.google.android.gms.ads.exoplayer1.extractor.mp4.f.a(:com.google.android.gms.dynamite_adsdynamite@16089056@16.0.89 (040800-239467275):42)
        at com.google.android.gms.ads.exoplayer1.extractor.h.c(:com.google.android.gms.dynamite_adsdynamite@16089056@16.0.89 (040800-239467275):21)
        at com.google.android.gms.ads.exoplayer1.upstream.r.run(:com.google.android.gms.dynamite_adsdynamite@16089056@16.0.89 (040800-239467275):9)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
```

**Comment by yoalex5** [comment]
I have figured out that the next .mp4 files cause the error

```
https://sneezy.aws.rubiconproject.com/rp-eng-soln/rp-qa-sites/videoTest/ad1/recycling_320_low.mp4
https://sneezy.aws.rubiconproject.com/rp-eng-soln/rp-qa-sites/videoTest/ad1/recycling_640_low.mp4
```

Log contains the next info:
ExoPlayerImpl: Init 1.3.1

As a result we can conclude that AM SDK v17.1.3 uses ExoPlayer v1.3.1

I have checked this .mp4 filed on demo app from [ExoPlayer repo v1.3.1](https://github.com/google/ExoPlayer/pull/449) and the error was reproduced

After updating AM SDK from v17.1.3 to the latest v18.2.0 the bug has disappeared. Moreover a log does not contain any information about ExoPlayer instead of it you can find references to MediaPlayer.

One more thing, to use AM SDK more than v18.x.x we should migrate to AndroidX

**Comment by bszekely1** [comment]
merged to master. Fix was addressed
