### ISSUE TITLE
ArrayIndexOutOfBoundsException in PrebidServerAdapter.java line 73

### ISSUE THREAD

**Issue by aielcbmDev** [prebid/prebid-mobile-android#244]
**Describe the bug**
ArrayIndexOutOfBoundsException in PrebidServerAdapter.java line 73

**To Reproduce**
Unfortunately we don't have the steps to reproduce the issue; only the crashlog from crashlytics. The issue occurs when updating to [Prebid SDK version 1.10](https://github.com/prebid/prebid-mobile-android/releases/tag/1.10). 

**Expected behavior**
The app does not crash

**Smartphone (please complete the following information):**
DEVICE 1:
- Brand: HUAWEI
- Model: HUAWEI P smart 2019
- Orientation: Portrait
- RAM free: 622.86 MB
- Disk free: 19.61 GB
- OS version: Android 10

DEVICE 2:
- Brand: samsung
- Model: Galaxy S20 5G
- Orientation: Portrait
- RAM free: 3.07 GB
- Disk free: 67.63 GB
- OS version: Android 11

**Additional context**
```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: src.length=10 srcPos=1 dst.length=10 dstPos=0 length=-1
       at java.lang.System.arraycopy(System.java)
       at java.util.ArrayList.batchRemove(ArrayList.java:726)
       at java.util.ArrayList.removeAll(ArrayList.java:690)
       at org.prebid.mobile.PrebidServerAdapter.stopRequest(PrebidServerAdapter.java:73)
       at org.prebid.mobile.DemandFetcher$RequestRunnable.cancelRequest(DemandFetcher.java:167)
       at org.prebid.mobile.DemandFetcher.destroy(DemandFetcher.java:120)
       at org.prebid.mobile.DemandFetcher$1.run(DemandFetcher.java:145)
       at android.os.Handler.handleCallback(Handler.java:888)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:8178)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

**Comment by yoalex5** [comment]
Hello @aielcbmDev

I could not reproduce this bug but I created PR(#245) which is based on my assumption that it is a multi-threading issue.
Could you  please check this fix inside your implementation?

thank you

**Comment by aielcbmDev** [comment]
Hi @yoalex5 ,

I hope you are safe and well.

We are having 4 different crashes on PrebidServerAdapter class:
1. [#243](https://github.com/prebid/prebid-mobile-android/issues/243)
2. [#244](https://github.com/prebid/prebid-mobile-android/issues/244)
3. [#246](https://github.com/prebid/prebid-mobile-android/issues/246)
4. [#247](https://github.com/prebid/prebid-mobile-android/issues/247)

I have not been able to reproduce the issue myself either. 

Just in case you want to try to reproduce these issues, we are displaying a list of items where we insert some Prebid ads on some specific positions. We also fetch the data using pagination so when the user reaches the end of the list more items are loaded and we insert more Prebid ads before displaying it.

Thank you for taking the time to look into this.

Regards!

**Comment by yoalex5** [comment]
Hello @aielcbmDev,

PR #245 covers these errors.
Could you please test it ?
