### ISSUE TITLE
AppInfoManager is calling View methods on another thread than the UI thread.

### ISSUE THREAD

**Issue by linean** [prebid/prebid-mobile-android#597]
**Describe the bug**
While testing Prebid with AppLovin, I've noticed that it causes a lot of runtime crashes because it tries to touch the UI outside the UI thread.

**Stacktrace:**
```
Fatal Exception: java.lang.IllegalStateException: Calling View methods on another thread than the UI thread.
       at com.android.webview.chromium.WebViewChromium.b(WebViewChromium.java:115)
       at com.android.webview.chromium.WebViewChromium.c(WebViewChromium.java:117)
       at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:45)
       at android.webkit.WebView.<init>(WebView.java:651)
       at android.webkit.WebView.<init>(WebView.java:581)
       at android.webkit.WebView.<init>(WebView.java:564)
       at android.webkit.WebView.<init>(WebView.java:551)
       at android.webkit.WebView.<init>(WebView.java:541)
       at org.prebid.mobile.rendering.utils.helpers.AppInfoManager.initUserAgent(AppInfoManager.java:105)
       at org.prebid.mobile.rendering.utils.helpers.AppInfoManager.init(AppInfoManager.java:42)
       at org.prebid.mobile.rendering.sdk.SdkInitializer.init(SdkInitializer.java:44)
       at org.prebid.mobile.PrebidMobile.initializeSdk(PrebidMobile.java:215)
       at com.applovin.mediation.adapters.PrebidMaxMediationAdapter.initialize(PrebidMaxMediationAdapter.java:51)
       at com.applovin.impl.mediation.g$1.run(g.java:110)
       at com.applovin.impl.mediation.g$11.run(g.java:58)
       at com.applovin.impl.mediation.g.a(g.java:19)
       at com.applovin.impl.mediation.g.a(g.java:11)
       at com.applovin.impl.mediation.e.a(e.java:5)
       at com.applovin.impl.mediation.e.a(e.java:4)
       at com.applovin.impl.mediation.b.a$1.run(a.java:64)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:784)
```

**Dependencies:**
- org.prebid:prebid-mobile-sdk:2.0.8
- org.prebid:prebid-mobile-sdk-max-adapters:2.0.8

**Smartphone (please complete the following information):**
<img width="435" alt="image" src="https://user-images.githubusercontent.com/17886739/223350681-8a9bc09f-883e-4e95-ac61-4db84c5a39c6.png">

<img width="429" alt="image" src="https://user-images.githubusercontent.com/17886739/223350895-265de00e-04f1-4125-8d5f-1c97914a6b91.png">

**Comment by YuriyVelichkoPI** [comment]
Hi @linean ! Thanks for the report! It will be fixed in the next release.

**Comment by ValentinPostindustria** [comment]
Hi. Also, it may lead to another error. We will fix them together. 
```
PrebidOmAdSessionManager   E  Did you add omsdk-android.aar? Failed to init openMeasurementSDK: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
     at android.os.Handler.<init>(Handler.java:204)
     at android.os.Handler.<init>(Handler.java:118)
     at com.iab.omid.library.prebidorg.internal.h.a(Unknown Source:10)
     at com.iab.omid.library.prebidorg.b.a(Unknown Source:17)
     at com.iab.omid.library.prebidorg.Omid.activate(Unknown Source:6)
     at org.prebid.mobile.rendering.session.manager.OmAdSessionManager.activateOmSdk(OmAdSessionManager.java:76)
     at org.prebid.mobile.rendering.sdk.SdkInitializer.init(SdkInitializer.java:47)
     at org.prebid.mobile.PrebidMobile.initializeSdk(PrebidMobile.java:231)
     at com.applovin.mediation.adapters.PrebidMaxMediationAdapter.initialize(PrebidMaxMediationAdapter.java:50)
     at com.applovin.impl.mediation.g$1.run(Unknown Source:100)
```

**Comment by YuriyVelichkoPI** [comment]
PR: #600
