### ISSUE TITLE
Don't use deprecated `new Handler()` constructor (without parameter)

### ISSUE THREAD

**Issue by JensSchmitt** [prebid/prebid-mobile-android#620]
please use the constructor with a `Looper` argument (for instance `new Handler(Looper.getMainLooper())`)!
otherwise there will be a crash when the current Looper has not `prepared()` yet.

**Comment by JensSchmitt** [comment]
It crashed when calling `AdUnit#fetchDemand` and `PrebidMobile#initializeSdk`...
```
Failed to initAdId: java.lang.RuntimeException: Can't create handler inside thread Thread[DefaultDispatcher-worker-7,5,main] that has not called Looper.prepare()
at android.os.Handler.<init>(Handler.java:227)
at android.os.Handler.<init>(Handler.java:129)
at org.prebid.mobile.rendering.utils.helpers.AdIdManager.initAdId(AdIdManager.java:61)
at org.prebid.mobile.rendering.networking.modelcontrollers.Requester.getAdId(Requester.java:128)
at org.prebid.mobile.rendering.networking.modelcontrollers.BidRequester.startAdRequest(BidRequester.java:43)
at org.prebid.mobile.rendering.bidding.loader.BidLoader.sendBidRequest(BidLoader.java:194)
at org.prebid.mobile.rendering.bidding.loader.BidLoader.load(BidLoader.java:145)
at org.prebid.mobile.AdUnit.fetchDemand(AdUnit.java:164)
at org.prebid.mobile.AdUnit.fetchDemand(AdUnit.java:97)
at ...
```

**Comment by ValentinPostindustria** [comment]
Hi. We agree that `Handler()` without parameters is unsafe and must be replaced. We will do it. But we need some deeper understanding. 
- Is this crash only in `2.1.0` or it was in `2.0.9`? 
- Do you call `fetchDemand()` in background thread?

**Comment by JensSchmitt** [comment]
> Hi. We agree that `Handler()` without parameters is unsafe and must be replaced. We will do it. But we need some deeper understanding.
> 
> * Is this crash only in `2.1.0` or it was in `2.0.9`?

Also in `2.0.9`
> * Do you call `fetchDemand()` in background thread?

No. `Dispatchers.main`
