### ISSUE TITLE
Calling initialize SDK from background thread doesn't initialize OM SDK

### ISSUE THREAD

**Issue by ValentinPostindustria** [prebid/prebid-mobile-android#623]
**Describe the bug**
OM SDK can't be initialized in a background thread. So when it is called from a background thread we need to move OM SDK initialization to the main one.  

Logs:
```
Did you add omsdk-android.aar? Failed to init openMeasurementSDK: java.lang.RuntimeException: Can't create handler inside thread Thread[Thread-5,5,main] that has not called Looper.prepare()
     at android.os.Handler.<init>(Handler.java:227)
     at android.os.Handler.<init>(Handler.java:129)
     at com.iab.omid.library.prebidorg.internal.h.a(Unknown Source:10)
     at com.iab.omid.library.prebidorg.b.a(Unknown Source:17)
     at com.iab.omid.library.prebidorg.Omid.activate(Unknown Source:6)
     at org.prebid.mobile.rendering.session.manager.OmAdSessionManager.activateOmSdk(OmAdSessionManager.java:88)
     at org.prebid.mobile.rendering.sdk.SdkInitializer.init(SdkInitializer.java:52)
     at org.prebid.mobile.PrebidMobile.initializeSdk(PrebidMobile.java:235)
     at org.prebid.mobile.prebidkotlindemo.CustomApplication$initPrebidSDK$1.invoke(CustomApplication.kt:51)
     at org.prebid.mobile.prebidkotlindemo.CustomApplication$initPrebidSDK$1.invoke(CustomApplication.kt:47)
```

**Comment by ValentinPostindustria** [comment]
The same problem for the calling `fetchDemand()` in a background thread:
```
Failed to initAdId: java.lang.RuntimeException: Can't create handler inside thread Thread[Thread-8,5,main] that has not called Looper.prepare()
   at android.os.Handler.<init>(Handler.java:227)
   at android.os.Handler.<init>(Handler.java:129)
   at org.prebid.mobile.rendering.utils.helpers.AdIdManager.initAdId(AdIdManager.java:61)
   at org.prebid.mobile.rendering.networking.modelcontrollers.Requester.getAdId(Requester.java:128)
   at org.prebid.mobile.rendering.networking.modelcontrollers.BidRequester.startAdRequest(BidRequester.java:43)
   at org.prebid.mobile.rendering.bidding.loader.BidLoader.sendBidRequest(BidLoader.java:194)
   at org.prebid.mobile.rendering.bidding.loader.BidLoader.load(BidLoader.java:145)
   at org.prebid.mobile.AdUnit.fetchDemand(AdUnit.java:165)
   at org.prebid.mobile.prebidkotlindemo.activities.ads.gam.original.GamOriginalApiDisplayBanner320x50Activity$createAd$2.invoke(GamOriginalApiDisplayBanner320x50Activity.kt:77)
   at org.prebid.mobile.prebidkotlindemo.activities.ads.gam.original.GamOriginalApiDisplayBanner320x50Activity$createAd$2.invoke(GamOriginalApiDisplayBanner320x50Activity.kt:76)

**Comment by ValentinPostindustria** [comment]
If OM SDK was initialized ( `initializeSdk()`) in a background thread, trying to open any rendering example causes the crash. But Prebid SDK is initialized successfully. It logs `Prebid SDK 2.1.0 initialized`. 
```
PrebidAdWebViewClient    E  onPageFinished failed for url: https://null/ : java.lang.NullPointerException: Attempt to invoke virtual method 'void com.iab.omid.library.prebidorg.devicevolume.d.c()' on a null object reference
     at com.iab.omid.library.prebidorg.internal.h.d(Unknown Source:23)
     at com.iab.omid.library.prebidorg.internal.c.c(Unknown Source:15)
     at com.iab.omid.library.prebidorg.adsession.a.start(Unknown Source:12)
     at org.prebid.mobile.rendering.session.manager.OmAdSessionManager.startAdSession(OmAdSessionManager.java:322)
     at org.prebid.mobile.rendering.models.AbstractCreative.startOmSession(AbstractCreative.java:306)
     at org.prebid.mobile.rendering.models.HTMLCreative.createOmAdSession(HTMLCreative.java:173)
     at org.prebid.mobile.rendering.views.AdViewManager.processTransaction(AdViewManager.java:476)
     at org.prebid.mobile.rendering.views.AdViewManager.onFetchingCompleted(AdViewManager.java:94)
     at org.prebid.mobile.rendering.loading.TransactionManager.onTransactionSuccess(TransactionManager.java:87)
     at org.prebid.mobile.rendering.loading.Transaction$CreativeFactoryListener.onSuccess(Transaction.java:226)
     at org.prebid.mobile.rendering.loading.CreativeFactory$CreativeFactoryCreativeResolutionListener.creativeReady(CreativeFactory.java:256)
     at org.prebid.mobile.rendering.models.HTMLCreative.webViewReadyToDisplay(HTMLCreative.java:208)
     at org.prebid.mobile.rendering.views.webview.PrebidWebViewBanner.preloaded(PrebidWebViewBanner.java:181)
     at org.prebid.mobile.rendering.views.webview.WebViewBase.adAssetsLoaded(WebViewBase.java:100)
     at org.prebid.mobile.rendering.views.webview.AdWebViewClient.onPageFinished(AdWebViewClient.java:90)
```

**Comment by YuriyVelichkoPI** [comment]
In this case, it's better to leave the complexity and ask publishers to initialize Prebid SDK on the main thread. 

If we allow publishers to initialize from the background and address OM SDK issue, we will have to support the same behavior for all future potential cases.  

In the scope of this issue, let's just add a note to the docs that the method `initializeSdk()` must be invoked on the main thread.

**Comment by YuriyVelichkoPI** [comment]
The docs have been updated.
