### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.ads.admanager.AdManagerAdView.loadAd(com.google.android.gms.ads.admanager.AdManagerAdRequest)' on a null object reference 

### ISSUE THREAD

**Issue by TomasRiker** [prebid/prebid-mobile-android#729]
I observed this crash while testing my app on Firebase Test Lab on a physical Xiaomi Redmi 6A running Android 8.1.0. Looks like a bug in Prebid to me. I haven't been able to reproduce it on my own device. The video of the test provided by Firebase Test Lab shows that a banner ad is loaded correctly at first, and when it's about to be refreshed, the app crashes.

Prebid mobile version: 2.1.8

Stack trace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.ads.admanager.AdManagerAdView.loadAd(com.google.android.gms.ads.admanager.AdManagerAdRequest)' on a null object reference
     FATAL EXCEPTION: main
Process: com.my.app, PID: 21899
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.ads.admanager.AdManagerAdView.loadAd(com.google.android.gms.ads.admanager.AdManagerAdRequest)' on a null object reference
	at b3.a.b(SourceFile:47)
	at org.prebid.mobile.AdUnit$1.b(SourceFile:72)
	at org.prebid.mobile.rendering.bidding.loader.BidLoader$1.c(SourceFile:298)
	at org.prebid.mobile.rendering.networking.BaseNetworkTask.d(SourceFile:107)
	at org.prebid.mobile.rendering.networking.BaseNetworkTask.onPostExecute(SourceFile:3)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.-wrap1(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6662)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by TomasRiker** [comment]
I'm sorry, it seems like the bug is in the code that uses Prebid, not Prebid itself.

**Comment by TomasRiker** [comment]
I'm sorry, it seems like the bug is in the code that uses Prebid, not Prebid itself.
